apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "conservation-tool.fullname.prefect-deploy" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conservation-tool.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ include "conservation-tool.fullname.prefect-deploy" . }}
    spec:
      serviceAccountName: deployer
      restartPolicy: Never
      containers:
        - name: prefect-deploy
          image: "{{ .Values.registry }}/{{ .Values.services.workflows.deploy.image.stream }}:{{ .Values.services.workflows.deploy.image.tag }}"
          imagePullPolicy: {{ .Values.services.workflows.deploy.image.pullPolicy | default "IfNotPresent" }}
          command:
            - bash
            - src/setup.sh
          ports:
            - containerPort: {{ .Values.ports.prefect_server_api | default 4201 }}
          env:
            - name: PREFECT_API_URL
              value: "{{ .Values.env.PREFECT_API_URL }}"
            - name: ZARR_STORE_PATH
              value: "{{ .Values.env.ZARR_STORE_PATH }}"
            - name: HOME
              value: "/home/app"
            - name: PREFECT_HOME
              value: "/tmp/.prefect"
            - name: MPLCONFIGDIR
              value: "/tmp/.config/matplotlib"
          resources:
            {{- toYaml .Values.services.workflows.deploy.resources | nindent 12 }}