apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conservation-tool.fullname.prefect-worker" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conservation-tool.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.workflows.worker.replicas }}
  selector:
    matchLabels:
      app: {{ include "conservation-tool.fullname.prefect-worker" . }}
  template:
    metadata:
      labels:
        app: {{ include "conservation-tool.fullname.prefect-worker" . }}
    spec:
      serviceAccountName: deployer
      containers:
        - name: prefect-worker
          image: "{{ .Values.registry }}/{{ .Values.services.workflows.worker.image.stream }}:{{ .Values.services.workflows.worker.image.tag }}"
          imagePullPolicy: {{ .Values.services.workflows.worker.image.pullPolicy | default "IfNotPresent" }}
          args:
            - prefect
            - worker
            - start
            - --pool
            - "{{ .Values.services.workflows.worker.pool }}"
          ports:
            - containerPort: {{ .Values.ports.prefect_worker_api | default 4202 }}
          env:
            - name: PREFECT_API_URL
              value: "{{ .Values.env.PREFECT_API_URL }}"
            - name: ZARR_STORE_PATH
              value: "{{ .Values.env.ZARR_STORE_PATH }}"
            - name: CONSERVATION_API_URL
              value: "{{ .Values.env.CONSERVATION_API_URL }}"
            - name: INTERNAL_API_KEY
              value: "{{ .Values.env.INTERNAL_API_KEY }}"
            - name: OBJECT_STORE_URL
              value: "{{ .Values.env.OBJECT_STORE_URL }}"
            - name: OBJECT_STORE_ACCESS_KEY_ID
              value: "{{ .Values.env.OBJECT_STORE_ACCESS_KEY_ID }}"
            - name: OBJECT_STORE_SECRET_KEY_ID
              value: "{{ .Values.env.OBJECT_STORE_SECRET_KEY_ID }}"
            - name: OBJECT_STORE_BUCKET_NAME
              value: "{{ .Values.env.OBJECT_STORE_BUCKET_NAME }}"
            - name: S3_KEY_PREFIX
              value: "{{ .Values.env.S3_KEY_PREFIX }}"
          resources:
            {{- toYaml .Values.services.workflows.worker.resources | nindent 12 }}
