apiVersion: v1
kind: Service
metadata:
  name: {{ include "conservation-tool.fullname.prefect-worker" . }}
  labels:
    {{- include "conservation-tool.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.workflows.worker.service.type }}
  selector:
    app: {{ include "conservation-tool.fullname.prefect-worker" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.services.workflows.worker.service.port }}
      targetPort: {{ .Values.services.workflows.worker.service.targetPort }}
