apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "conservation-tool.fullname.frontend" . }}
  labels:
    app: {{ include "conservation-tool.fullname.frontend" . }}
spec:
  to:
    kind: Service
    name: {{ include "conservation-tool.fullname.frontend" . }}
  port:
    targetPort: {{ .Values.services.frontend.service.targetPort | default 7070 }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect